server:
#配置服务器
  port: 8090
spring:
  mvc:
    view:
    #配置访问jsp页面的前后缀
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  #数据源的配置
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tb?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#配置相关的mybatis
mybatis:
#扫描所有mapperr.xml文件
  mapper-locations: classpath:mapper/*.xml
  #给实体封装类配置别名：默认就是类名
  type-aliases-package: cn.kgc.entity



